import { COLORS } from './colors.js';

// All inline-style presets live here. UI components import this object and
// reference styles.<key>. To restyle visually, change values here.

export const styles = {
  app: {
    minHeight: '100vh',
    background: COLORS.bg,
    color: COLORS.text,
    fontFamily: "'Oswald', sans-serif",
  },
  header: {
    padding: '16px 28px',
    background: COLORS.panel,
    borderBottom: `1px solid ${COLORS.border}`,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 16,
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  },
  headerLeft: { display: 'flex', alignItems: 'center', gap: 24 },
  logo:       { display: 'flex', alignItems: 'baseline', gap: 8, cursor: 'pointer' },
  logoMark:   { color: COLORS.accent, fontSize: 24 },
  logoText:   { fontFamily: "'Bebas Neue'", fontSize: 28, letterSpacing: 3 },
  logoSub:    { fontSize: 11, letterSpacing: 4, opacity: 0.5 },
  seasonBadge: {
    display: 'flex', flexDirection: 'column', alignItems: 'center',
    padding: '4px 14px', border: `1px solid ${COLORS.accent}`, borderRadius: 4,
  },
  nav:    { display: 'flex', gap: 8, flexWrap: 'wrap' },
  navBtn: {
    padding: '8px 16px',
    fontFamily: "'Oswald', sans-serif",
    fontSize: 13,
    letterSpacing: 1.5,
    fontWeight: 600,
    border: `1px solid ${COLORS.borderMute}`,
    borderRadius: 6,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  main: { padding: '24px 28px', maxWidth: 1400, margin: '0 auto' },
  sectionTitle:     { display: 'flex', alignItems: 'center', gap: 14, marginBottom: 20 },
  sectionTitleBar:  { width: 6, height: 36, background: COLORS.accent },
  sectionTitleMain: { fontFamily: "'Bebas Neue'", fontSize: 32, letterSpacing: 2, lineHeight: 1 },
  sectionTitleSub:  { fontSize: 12, letterSpacing: 2, opacity: 0.5, marginTop: 4 },
  chip: {
    padding: '6px 14px', fontSize: 11, fontFamily: "'JetBrains Mono'",
    letterSpacing: 1, border: `1px solid ${COLORS.borderMute}`, borderRadius: 14, cursor: 'pointer',
    fontWeight: 600,
  },
  teamGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: 14,
  },
  teamCard: {
    background: COLORS.panel,
    border: `1px solid ${COLORS.border}`,
    borderLeft: `5px solid ${COLORS.borderMute}`,
    borderRadius: 8,
    padding: 18,
    cursor: 'pointer',
    transition: 'transform 0.15s, box-shadow 0.15s, border-color 0.15s',
    boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
  },
  teamCardTop:  { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14 },
  teamCardCity: { fontSize: 11, letterSpacing: 2, opacity: 0.5 },
  teamCardName: { fontFamily: "'Bebas Neue'", fontSize: 26, letterSpacing: 1, lineHeight: 1, marginTop: 2 },
  rankBadge: {
    fontFamily: "'JetBrains Mono'", fontSize: 11, padding: '4px 10px',
    background: COLORS.border, borderRadius: 12, opacity: 0.7, fontWeight: 700,
  },
  recordLine: { display: 'flex', alignItems: 'baseline', gap: 8, marginBottom: 10 },
  recordBig:  { fontFamily: "'JetBrains Mono'", fontSize: 22, fontWeight: 700 },
  recordSub:  { fontSize: 11, opacity: 0.5, letterSpacing: 1 },
  statRow:    { display: 'flex', gap: 6, marginBottom: 10, flexWrap: 'wrap' },
  tierPill: {
    fontSize: 10, fontWeight: 700, padding: '4px 10px', borderRadius: 12,
    color: COLORS.text, letterSpacing: 0.8, textTransform: 'uppercase',
  },
  momentumBar: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
    padding: '10px 0 0', borderTop: `1px solid ${COLORS.border}`,
  },
  bigBtn: {
    padding: '16px 28px',
    background: COLORS.accent,
    color: COLORS.accentText,
    border: 'none',
    borderRadius: 8,
    fontFamily: "'Bebas Neue'",
    fontSize: 22,
    letterSpacing: 2,
    cursor: 'pointer',
    transition: 'all 0.2s',
    width: '100%',
    fontWeight: 700,
    boxShadow: '0 4px 12px rgba(213,10,10,0.25)',
  },
  backBtn: {
    background: 'none', border: `1px solid ${COLORS.borderMute}`, color: COLORS.textMute,
    padding: '6px 14px', fontFamily: "'Oswald'", fontSize: 12, letterSpacing: 1.5,
    cursor: 'pointer', marginBottom: 16, borderRadius: 6,
  },
  teamHeader: {
    padding: 32, borderRadius: 10, marginBottom: 24, color: '#fff',
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
  },
  detailGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 },
  detailCard: {
    background: COLORS.panel, border: `1px solid ${COLORS.border}`,
    borderRadius: 8, padding: 20,
    boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
  },
  detailH4: {
    margin: 0, marginBottom: 14, fontFamily: "'Bebas Neue'", fontSize: 18,
    letterSpacing: 2, color: COLORS.accent, borderBottom: `1px solid ${COLORS.border}`, paddingBottom: 8,
  },
  rosterGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 12 },
  playerCard: {
    background: COLORS.panelDeep, border: '2px solid', borderRadius: 8, padding: 14,
  },
  rarityBadge: {
    fontSize: 10, fontWeight: 700, padding: '4px 9px', borderRadius: 12,
    color: COLORS.textOnDark, letterSpacing: 0.8, display: 'inline-block', textTransform: 'uppercase',
  },
  weekHeader: {
    fontFamily: "'Bebas Neue'", fontSize: 22, letterSpacing: 3,
    color: COLORS.accent, marginTop: 0, marginBottom: 12,
    borderBottom: `1px solid ${COLORS.border}`, paddingBottom: 6,
  },
  gameGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 10 },
  gameCard: {
    background: COLORS.panel, border: `1px solid ${COLORS.border}`,
    borderRadius: 8, padding: 14,
    transition: 'transform 0.15s, box-shadow 0.15s, border-color 0.15s',
  },
  gameTeamRow:   { display: 'flex', alignItems: 'center', gap: 10, padding: '5px 0' },
  gameTeamDot:   { width: 10, height: 10, borderRadius: 2 },
  gameTeamLabel: { flex: 1, fontSize: 13, letterSpacing: 0.5, fontWeight: 600 },
  gameScore:     { fontFamily: "'JetBrains Mono'", fontSize: 18, fontWeight: 700 },
  gameMvp: {
    fontSize: 11, letterSpacing: 1, marginTop: 8,
    borderTop: `1px solid ${COLORS.border}`, paddingTop: 6,
  },
  offGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 },
  faRow: {
    display: 'flex', alignItems: 'center', gap: 10, padding: '8px 0',
    borderBottom: `1px solid ${COLORS.border}`, fontSize: 13,
  },
  tradeRow: {
    display: 'flex', alignItems: 'center', gap: 16, padding: 12,
    borderBottom: `1px solid ${COLORS.border}`,
  },
  tradeSide: { flex: 1, fontSize: 13 },
  standingsTable: { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th:    { textAlign: 'left',  padding: '8px 10px', fontSize: 11, letterSpacing: 1, opacity: 0.5, fontWeight: 600 },
  thNum: { textAlign: 'right', padding: '8px 10px', fontSize: 11, letterSpacing: 1, opacity: 0.5, fontWeight: 600 },
  standingRow: { cursor: 'pointer', transition: 'background 0.15s' },
  td:    { padding: '8px 10px', borderTop: `1px solid ${COLORS.border}` },
  tdNum: { padding: '8px 10px', borderTop: `1px solid ${COLORS.border}`, textAlign: 'right', fontFamily: "'JetBrains Mono'" },
  teamDot: { display: 'inline-block', width: 10, height: 10, borderRadius: 2, marginRight: 8 },
  starGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(360px, 1fr))', gap: 10 },
  playerRow: {
    display: 'flex', alignItems: 'center', gap: 12, padding: 14,
    background: COLORS.panel, border: `1px solid ${COLORS.border}`,
    borderLeft: `5px solid ${COLORS.borderMute}`,
    borderRadius: 8, cursor: 'pointer', transition: 'all 0.15s',
  },
};

export const globalCSS = `
  * { box-sizing: border-box; }
  body { margin: 0; }
`;
